# Generated by Django 3.1.7 on 2021-03-09 09:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('long_url', models.URLField(unique=True)),
                ('short_url', models.CharField(default=main.models.generate_random_string, max_length=6, primary_key=True, serialize=False)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
